#!/usr/bin/env bash
# Use this tmux-sharing-users script in your tmux config to ease multi-user
# pairing, by adding these lines to your ~/.tmux.conf:

#   set-option -g status-interval 10
#   set-option -g status-left-length 50
#   set-option -g status-left '#{user} #(/usr/local/bin/tmux-sharing-users)'

# IMPORTANT: When running 'tmux' from outside your session, you will get an
# "unsafe permissions" error. For you or others to connect to your server, use -S:
#   tmux -S /tmp/tmux-<username>-default attach

path="${TMUX%,*,*}"

allow-dir() {
    if [ "$USER" == $(stat -c%U "$1") ]; then
        allow-dir $(dirname "$1")
        chmod a+x "$1"
    fi
}

if [ "666" != $(stat -c%a "$path") ]; then
    allow-dir $(dirname "$path")
    chmod 666 "$path"
fi

ln -fs "$path" "/tmp/tmux-$USER-$(basename "$path")"

echo \($(stat -c %U $(tmux list-clients -F '#{client_name}') | grep -v $USER)\)

# RATIONALE:
# No need to install anything, just copy the file and update your ~/.tmux.conf
# Once set up, it's totally automatic: all sessions are always ready to share
# Con: Some normal tmux commands (new-session, attach) generate an "unsafe
# permissions" error. The workaround is to use -S specifically.
# Con: No annoucement immediately when a new user connects

# ALTERNATIVES:
# Wrap invocations of tmux with some new command (see tmix, tmux-share)
