#!/usr/bin/env bash
# Use this tmux-share-users script to ease multi-user pairing, by adding these
# lines to your ~/.tmux.conf:

#   set-option -g status-interval 10
#   set-option -g status-left-length 50
#   set-option -g status-left '#{user} #(/usr/local/bin/tmux-share-users) '

# IMPORTANT: When running 'tmux' from outside an existing session, you will get
# an "unsafe permissions" error. For you or others to connect to your server,
# use -S:
#   tmux -S /tmp/tmux-<username>-default attach

path="${TMUX%,*,*}"

allow-dir() {
    if [ "$USER" == $(stat -c%U "$1") ]; then
        allow-dir $(dirname "$1")
        chmod a+x "$1"
    fi
}

if [ "666" != $(stat -c%a "$path") ]; then
    allow-dir $(dirname "$path")
    chmod 666 "$path"
fi

ln -fs "$path" "/tmp/tmux-$USER-$(basename "$path")"

echo \($(stat -c%U $(tmux list-clients -F '#{client_name}') | grep -v $USER)\)
